### PR TITLE
#157 Add viem support and related tests

### PR DESCRIPTION
**Pull request by muhammetaliakbay**
Related issue: https://github.com/cgewecke/hardhat-gas-reporter/issues/157

This PR
- adds `viem` support and tests
- upgrades typescript
- replaces `EGRDataCollectionProvider` with `SnifferProvider`
- integrates `extendEnvironment` to inject sniffer provider

### CODE REVIEW

**Comment by gionn** [comment]
@cgewecke any feedback on this?

**Comment by cgewecke** [comment]
@muhammetaliakbay @gionn Thanks so much for this and apologies for taking so long to review.

Could someone link to the relevant code at viem or hardhat where the freezing described below happens?

> Injecting the modified provider in TASK_TEST_RUN_MOCHA_TESTS sub task is too late as viem reads and freezes the provider instance on the module load

I'm a a little worried about configuring the provider for gas logging in an `extendEnvironment` hook because AFAIK.it will execute for every task hardhat runs. It might come into conflict with other plugins and is difficult to enable/disable conditionally. 

That said there is also a new [extendProvider][1] hook available in more recent HH versions which seems to be designed for this kind of application. Does using that have same freezing problem? 

(Will pull this PR down this week and take a closer look to see if there are any other issues...thanks for all the work you've already put into this). 

[1]: https://hardhat.org/hardhat-runner/docs/advanced/building-plugins#extending-the-hardhat-provider

**Comment by transmental** [comment]
pls merge this

**Review by cgewecke — COMMENTED** [review]
Thank you for preparing such a great set of tests for this - I would not have caught that there is a problem with transactions executed with the wallet clients. 

Debugged that at Hardhat and think the problem is that in the extendEnviroment hook at the hardhat-viem plugin, [the provider is passed directly as an argument to the  viem wrapper methods on definition][1] instead of being de-referenced dynamically when the methods are called. As such those methods never refer to the provider which is redefined in the test task here. 

The main concern I have with the approach in this PR is that it uses extendEnvironment. As you note, the plugins have to be loaded in a specific sequence in hardhat.config.ts for them to work together...I think a more reliable way is to use Hardhat's new extendProvider hook, but that's a breaking change I'd like to introduce in 2.0

For the moment, I'm going to publish this branch at a special tag (viem), pin your original issue and direct people to this work-around.

[1]: https://github.com/NomicFoundation/hardhat/blob/2f5c30cec52434e6a798dadfd314979c7fd4c742/packages/hardhat-viem/src/index.ts#L18

**Pull request closed without merging**
